import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, AlertTriangle, Check, Clipboard, Clock3, Edit3, HeartPulse, KeyRound, Link2, PauseCircle, PlayCircle, RefreshCcw, Save, Settings2, ShieldCheck, Trash2, Zap } from "lucide-react";
import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { adapterConflictPolicyLabel, adapterConflictPolicyValue, adapterConnectionStatusLabel, adapterExecutionModeLabel, adapterExecutionModeValue, credentialStatusLabel, ingestionOperationalStateLabel, ingestionRunStatusLabel } from "../../api/labels";
import type { AdapterConnection, AdapterConnectionHealth, AdapterIngressCredential, AdapterIngressCredentialListResponse, AdapterTypeCapability, CreateAdapterIngressCredentialResponse } from "../../api/types";
import { useSession } from "../../app/session";
import { ErrorState, LoadingState, Modal, StatusBadge } from "../../components/ui/primitives";

type ConnectionTab = "health" | "settings" | "credentials";
type ConfirmAction = "enable" | "disable" | "reset-checkpoint" | "clear-schedule";

export function ConnectionDetail({ propertyId, connectionId, adapterTypes, canManage, canManageCredentials, onClose }: { propertyId: string; connectionId: string | null; adapterTypes: AdapterTypeCapability[]; canManage: boolean; canManageCredentials: boolean; onClose: () => void }) {
  const { request } = useSession();
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<ConnectionTab>("health");
  const [editing, setEditing] = useState(false);
  const [confirmAction, setConfirmAction] = useState<ConfirmAction | null>(null);
  useEffect(() => { setTab("health"); setEditing(false); setConfirmAction(null); }, [connectionId]);
  const connection = useQuery({ queryKey: ["ingestion-connection", propertyId, connectionId], queryFn: () => request<AdapterConnection>(`/api/ingestion/properties/${propertyId}/connections/${connectionId}`), enabled: Boolean(connectionId) });
  const health = useQuery({ queryKey: ["ingestion-connection-health", propertyId, connectionId], queryFn: () => request<AdapterConnectionHealth>(`/api/ingestion/properties/${propertyId}/connections/${connectionId}/health`), enabled: Boolean(connectionId) && tab === "health", refetchInterval: 30_000 });
  async function refresh(updated?: AdapterConnection) { if (updated && connectionId) queryClient.setQueryData(["ingestion-connection", propertyId, connectionId], updated); await Promise.all([queryClient.invalidateQueries({ queryKey: ["ingestion-connections", propertyId] }), queryClient.invalidateQueries({ queryKey: ["ingestion-connection-health", propertyId, connectionId] })]); }
  const actionMutation = useMutation({ mutationFn: ({ item, action }: { item: AdapterConnection; action: ConfirmAction }) => request<AdapterConnection>(`/api/ingestion/properties/${propertyId}/connections/${item.connectionId}/${action === "clear-schedule" ? "polling-schedule/clear" : action}`, { method: "POST", body: JSON.stringify({ expectedVersion: item.version }) }), onSuccess: async (updated) => { setConfirmAction(null); await refresh(updated); } });
  const updateMutation = useMutation({ mutationFn: ({ item, payload }: { item: AdapterConnection; payload: Record<string, unknown> }) => request<AdapterConnection>(`/api/ingestion/properties/${propertyId}/connections/${item.connectionId}`, { method: "PUT", body: JSON.stringify({ ...payload, expectedVersion: item.version }) }), onSuccess: async (updated) => { setEditing(false); await refresh(updated); } });
  const scheduleMutation = useMutation({ mutationFn: ({ item, intervalSeconds, maxAttempts }: { item: AdapterConnection; intervalSeconds: number; maxAttempts: number }) => request<AdapterConnection>(`/api/ingestion/properties/${propertyId}/connections/${item.connectionId}/polling-schedule`, { method: "PUT", body: JSON.stringify({ intervalSeconds, maxAttempts, expectedVersion: item.version }) }), onSuccess: refresh });
  const item = connection.data;
  const capability = adapterTypes.find((entry) => entry.adapterType === item?.adapterType);
  return <Modal open={Boolean(connectionId)} size="lg" title={item?.adapterType || "Integration connection"} description={item ? `${adapterExecutionModeLabel(item.executionMode)} · connection ${item.connectionId.slice(0, 8).toUpperCase()}` : "Loading connection"} onClose={onClose}>{connection.isLoading ? <LoadingState label="Loading connection" /> : connection.error ? <ErrorState error={connection.error} retry={() => void connection.refetch()} /> : item ? <div className="space-y-5">
    <div className="flex flex-col gap-4 rounded-2xl bg-base-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-base-content/40">Connection</p><p className="mt-1 font-semibold">{item.configurationReference}</p><p className="mt-1 text-xs text-base-content/50">{adapterConflictPolicyLabel(item.conflictPolicy)}</p></div><div className="flex flex-wrap items-center gap-2"><StatusBadge status={adapterConnectionStatusLabel(item.status)} />{canManage && adapterConnectionStatusLabel(item.status) === "enabled" && <button type="button" className="btn btn-ghost btn-sm" onClick={() => setConfirmAction("disable")}><PauseCircle size={15} />Disable</button>}{canManage && adapterConnectionStatusLabel(item.status) === "disabled" && <button type="button" className="btn btn-primary btn-sm" onClick={() => setConfirmAction("enable")}><PlayCircle size={15} />Enable</button>}</div></div>
    {confirmAction && <ConnectionConfirmation action={confirmAction} connection={item} submitting={actionMutation.isPending} error={actionMutation.error} onCancel={() => { setConfirmAction(null); actionMutation.reset(); }} onConfirm={() => actionMutation.mutate({ item, action: confirmAction })} />}
    <div role="tablist" aria-label="Connection details" className="tabs tabs-box grid grid-cols-3 bg-base-200 p-1">{(["health", "settings", "credentials"] as const).map((value) => <button key={value} role="tab" aria-selected={tab === value} className={`tab gap-1.5 text-xs font-semibold sm:text-sm ${tab === value ? "tab-active bg-base-100 shadow-sm" : ""}`} onClick={() => setTab(value)}>{value === "health" ? <HeartPulse size={15} /> : value === "settings" ? <Settings2 size={15} /> : <KeyRound size={15} />}{capitalize(value)}</button>)}</div>
    {tab === "health" && <ConnectionHealth query={health} />}
    {tab === "settings" && <div className="space-y-5"><section className="rounded-2xl border border-base-300 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-display text-lg font-semibold">Connection settings</h3><p className="mt-1 text-xs text-base-content/50">Execution, conflict handling, and configuration references.</p></div>{canManage && !editing && <button type="button" className="btn btn-ghost btn-sm text-primary" onClick={() => setEditing(true)}><Edit3 size={15} />Edit</button>}</div>{editing ? <ConnectionSettingsForm connection={item} capability={capability} submitting={updateMutation.isPending} error={updateMutation.error} onCancel={() => { setEditing(false); updateMutation.reset(); }} onSave={(payload) => updateMutation.mutate({ item, payload })} /> : <ConnectionSettingsReadOnly connection={item} />}</section><PollingSchedule connection={item} capability={capability} canManage={canManage} submitting={scheduleMutation.isPending || actionMutation.isPending} error={scheduleMutation.error || actionMutation.error} onConfigure={(intervalSeconds, maxAttempts) => scheduleMutation.mutate({ item, intervalSeconds, maxAttempts })} onClear={() => setConfirmAction("clear-schedule")} />{canManage && item.checkpoint && <section className="rounded-2xl border border-warning/25 bg-warning/8 p-4"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">Processing checkpoint</h3><p className="mt-1 break-all text-xs text-base-content/55">{item.checkpoint}</p><p className="mt-2 text-xs text-base-content/50">Reset only when the adapter must replay data from its initial position.</p></div><button type="button" className="btn btn-ghost btn-sm shrink-0 text-error" onClick={() => setConfirmAction("reset-checkpoint")}><RefreshCcw size={15} />Reset</button></div></section>}</div>}
    {tab === "credentials" && <CredentialsPanel propertyId={propertyId} connection={item} canManage={canManageCredentials} />}
    <div className="flex justify-end border-t border-base-300 pt-5"><button type="button" className="btn btn-ghost" onClick={onClose}>Close</button></div>
  </div> : null}</Modal>;
}

function ConnectionHealth({ query }: { query: { isLoading: boolean; error: unknown; data?: AdapterConnectionHealth; refetch: () => Promise<unknown> } }) {
  if (query.isLoading) return <LoadingState label="Evaluating connection health" />;
  if (query.error) return <ErrorState error={query.error} retry={() => void query.refetch()} />;
  const health = query.data; if (!health) return null;
  const healthy = [4, 8, "lastRunSucceeded", "observationsReceived"].includes(health.operationalState);
  return <div className="space-y-5"><section className={`rounded-2xl border p-5 ${healthy ? "border-primary/20 bg-primary/5" : "border-base-300"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><div className={`grid size-10 place-items-center rounded-xl ${healthy ? "bg-primary text-primary-content" : "bg-base-200 text-base-content/60"}`}>{healthy ? <Check size={18} /> : <Activity size={18} />}</div><div><h3 className="font-display text-lg font-semibold capitalize">{ingestionOperationalStateLabel(health.operationalState)}</h3><p className="mt-1 text-xs text-base-content/50">Evaluated {formatDateTime(health.evaluatedAtUtc)}</p></div></div>{health.latestRunStatus != null && <StatusBadge status={ingestionRunStatusLabel(health.latestRunStatus)} />}</div>{health.latestRunError && <p className="mt-4 rounded-xl bg-error/8 p-3 text-sm text-error">{health.latestRunError}</p>}</section><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Pending receipts" value={health.pendingReceiptCount} /><Metric label="Rejected receipts" value={health.rejectedReceiptCount} tone={health.rejectedReceiptCount ? "warning" : undefined} /><Metric label="Last success" value={health.lastSuccessfulRunAtUtc ? timeAgo(health.lastSuccessfulRunAtUtc) : "Never"} /><Metric label="Last observation" value={health.lastObservationReceivedAtUtc ? timeAgo(health.lastObservationReceivedAtUtc) : "Never"} /></div><div className="grid gap-3 sm:grid-cols-2"><InfoRow icon={<Clock3 />} label="Next run expected" value={health.nextRunExpectedAtUtc ? formatDateTime(health.nextRunExpectedAtUtc) : health.runExpected ? "Schedule pending" : "Not scheduled"} /><InfoRow icon={<ShieldCheck />} label="Adapter capability" value={capabilityStatusLabel(health.capabilityStatus)} /></div>{(health.expiredRawPayloadCount > 0 || health.dueSensitiveHistoryCount > 0 || health.activeLegalHoldCount > 0) && <section className="rounded-2xl border border-base-300 p-4"><h3 className="font-semibold">Retention signals</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><Metric label="Expired payloads" value={health.expiredRawPayloadCount} /><Metric label="History due" value={health.dueSensitiveHistoryCount} /><Metric label="Active legal holds" value={health.activeLegalHoldCount} /></div></section>}</div>;
}

function ConnectionSettingsReadOnly({ connection }: { connection: AdapterConnection }) { return <div className="grid gap-3 sm:grid-cols-2"><InfoRow icon={<Zap />} label="Execution mode" value={adapterExecutionModeLabel(connection.executionMode)} /><InfoRow icon={<ShieldCheck />} label="Conflict policy" value={adapterConflictPolicyLabel(connection.conflictPolicy)} /><InfoRow icon={<Link2 />} label="Configuration reference" value={connection.configurationReference} /><InfoRow icon={<KeyRound />} label="Secret reference" value={connection.hasSecretReference ? "Configured" : "Not configured"} /></div>; }

function ConnectionSettingsForm({ connection, capability, submitting, error, onCancel, onSave }: { connection: AdapterConnection; capability?: AdapterTypeCapability; submitting: boolean; error: unknown; onCancel: () => void; onSave: (payload: Record<string, unknown>) => void }) {
  const resolvedMode = executionModeKey(connection.executionMode); const initialMode = resolvedMode === "unknown" ? "polling" : resolvedMode; const initialPolicy = conflictPolicyKey(connection.conflictPolicy); const [mode, setMode] = useState(initialMode); const [policy, setPolicy] = useState(initialPolicy); const [configurationReference, setConfigurationReference] = useState(connection.configurationReference); const [secretReference, setSecretReference] = useState(""); const [clearSecret, setClearSecret] = useState(false); const supportedModes = capability?.executionModes.map(executionModeKey).filter((value): value is "polling" | "continuous" | "push" | "remotePolling" => value !== "unknown") ?? ["polling", "continuous", "push", "remotePolling"];
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSave({ executionMode: adapterExecutionModeValue(mode), conflictPolicy: adapterConflictPolicyValue(policy), configurationReference: configurationReference.trim(), secretReference: clearSecret ? null : emptyStringToNull(secretReference), clearSecretReference: clearSecret }); }
  return <form className="space-y-4" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Execution mode" value={mode} onChange={(value) => setMode(value as typeof mode)} options={supportedModes.map((value) => ({ value, label: capitalize(adapterExecutionModeLabel(value)) }))} /><SelectField label="Conflict policy" value={policy} onChange={(value) => setPolicy(value as typeof policy)} options={[{ value: "suggestionsOnly", label: "Suggestions only" }, { value: "autoApplyWhenAdapterBaselineUnchanged", label: "Auto-apply safe updates" }]} /></div><TextInput label="Configuration reference" value={configurationReference} onChange={setConfigurationReference} /><div><TextInput label="New secret reference (optional)" value={secretReference} onChange={setSecretReference} disabled={clearSecret} /><label className="mt-2 flex cursor-pointer items-center gap-2 text-sm"><input className="checkbox checkbox-sm" type="checkbox" checked={clearSecret} onChange={(event) => setClearSecret(event.target.checked)} />Clear the existing secret reference</label></div>{Boolean(error) && <ErrorState error={error} />}<div className="flex justify-end gap-2"><button type="button" className="btn btn-ghost btn-sm" onClick={onCancel} disabled={submitting}>Cancel</button><button type="submit" className="btn btn-primary btn-sm" disabled={submitting || !configurationReference.trim()}>{submitting ? <span className="loading loading-spinner loading-xs" /> : <Save size={15} />}Save settings</button></div></form>;
}

function PollingSchedule({ connection, capability, canManage, submitting, error, onConfigure, onClear }: { connection: AdapterConnection; capability?: AdapterTypeCapability; canManage: boolean; submitting: boolean; error: unknown; onConfigure: (intervalSeconds: number, maxAttempts: number) => void; onClear: () => void }) {
  const pollingMode = ["polling", "remotePolling"].includes(executionModeKey(connection.executionMode)); const recommended = Number(capability?.recommendedPollingIntervalSeconds ?? 300); const minimum = Number(capability?.minimumPollingIntervalSeconds ?? 30); const [editing, setEditing] = useState(false); const [interval, setInterval] = useState(String(connection.pollingIntervalSeconds ?? recommended)); const [attempts, setAttempts] = useState(String(connection.pollingScheduleMaxAttempts ?? 3));
  if (!pollingMode) return <section className="rounded-2xl border border-base-300 p-4"><h3 className="font-semibold">Polling schedule</h3><p className="mt-1 text-sm text-base-content/55">This execution mode does not use a BunkFy polling schedule.</p></section>;
  return <section className="rounded-2xl border border-base-300 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-lg font-semibold">Polling schedule</h3><p className="mt-1 text-xs text-base-content/50">{connection.pollingIntervalSeconds ? `Every ${formatDuration(connection.pollingIntervalSeconds)} · up to ${connection.pollingScheduleMaxAttempts} attempts` : "No polling schedule configured."}</p></div>{canManage && !editing && <div className="flex gap-2">{connection.pollingIntervalSeconds && <button type="button" className="btn btn-ghost btn-sm text-error" onClick={onClear}>Clear</button>}<button type="button" className="btn btn-ghost btn-sm text-primary" onClick={() => setEditing(true)}><Edit3 size={15} />{connection.pollingIntervalSeconds ? "Change" : "Configure"}</button></div>}</div>{editing && <form className="mt-4 grid gap-4 rounded-xl bg-base-200 p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end" onSubmit={(event) => { event.preventDefault(); onConfigure(Number(interval), Number(attempts)); }}><label className="form-control block"><span className="label-text mb-2 block text-sm font-semibold">Interval (seconds)</span><input className="input input-bordered w-full" type="number" min={minimum} value={interval} onChange={(event) => setInterval(event.target.value)} required /></label><label className="form-control block"><span className="label-text mb-2 block text-sm font-semibold">Maximum attempts</span><input className="input input-bordered w-full" type="number" min="1" value={attempts} onChange={(event) => setAttempts(event.target.value)} required /></label><div className="flex gap-2"><button type="button" className="btn btn-ghost btn-sm" onClick={() => setEditing(false)}>Cancel</button><button type="submit" className="btn btn-primary btn-sm" disabled={submitting}>{submitting && <span className="loading loading-spinner loading-xs" />}Save</button></div></form>}{Boolean(error) && <div className="mt-4"><ErrorState error={error} /></div>}</section>;
}

function CredentialsPanel({ propertyId, connection, canManage }: { propertyId: string; connection: AdapterConnection; canManage: boolean }) {
  const { request } = useSession(); const queryClient = useQueryClient(); const [creating, setCreating] = useState(false); const [issued, setIssued] = useState<CreateAdapterIngressCredentialResponse | null>(null); const credentials = useQuery({ queryKey: ["ingestion-credentials", propertyId, connection.connectionId], queryFn: () => request<AdapterIngressCredentialListResponse>(`/api/ingestion/properties/${propertyId}/connections/${connection.connectionId}/credentials?page=1&pageSize=100`) }); const createMutation = useMutation({ mutationFn: ({ label, expiresAtUtc }: { label: string; expiresAtUtc: string }) => request<CreateAdapterIngressCredentialResponse>(`/api/ingestion/properties/${propertyId}/connections/${connection.connectionId}/credentials`, { method: "POST", body: JSON.stringify({ label, expiresAtUtc }) }), onSuccess: async (result) => { setIssued(result); setCreating(false); await queryClient.invalidateQueries({ queryKey: ["ingestion-credentials", propertyId, connection.connectionId] }); } }); const revokeMutation = useMutation({ mutationFn: (credential: AdapterIngressCredential) => request<AdapterIngressCredential>(`/api/ingestion/properties/${propertyId}/connections/${connection.connectionId}/credentials/${credential.credentialId}/revoke`, { method: "POST", body: JSON.stringify({ expectedVersion: credential.version }) }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["ingestion-credentials", propertyId, connection.connectionId] }); } });
  return <div className="space-y-4">{issued && <IssuedToken result={issued} onDone={() => setIssued(null)} />}<section className="rounded-2xl border border-base-300 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-lg font-semibold">Ingress credentials</h3><p className="mt-1 text-xs text-base-content/50">Credentials authenticate push or remote adapter workers. Tokens are shown once.</p></div>{canManage && !creating && <button type="button" className="btn btn-primary btn-sm" onClick={() => setCreating(true)}><KeyRound size={15} />Issue credential</button>}</div>{creating && <CredentialForm submitting={createMutation.isPending} error={createMutation.error} onCancel={() => { setCreating(false); createMutation.reset(); }} onCreate={(label, expiresAtUtc) => createMutation.mutate({ label, expiresAtUtc })} />}</section>{credentials.isLoading ? <LoadingState label="Loading credentials" /> : credentials.error ? <ErrorState error={credentials.error} retry={() => void credentials.refetch()} /> : credentials.data?.credentials.length ? <div className="space-y-3">{credentials.data.credentials.map((credential) => <article key={credential.credentialId} className="rounded-2xl border border-base-300 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h4 className="font-semibold">{credential.label}</h4><StatusBadge status={credentialStatusLabel(credential.status)} /></div><p className="mt-1 text-xs text-base-content/50">Slot {credential.slot} · expires {formatDateTime(credential.expiresAtUtc)}</p>{credential.lastAuthenticatedAtUtc && <p className="mt-1 text-xs text-base-content/45">Last used {timeAgo(credential.lastAuthenticatedAtUtc)}</p>}</div>{canManage && credentialStatusLabel(credential.status) === "active" && <button type="button" className="btn btn-ghost btn-sm text-error" onClick={() => revokeMutation.mutate(credential)} disabled={revokeMutation.isPending}><Trash2 size={15} />Revoke</button>}</div></article>)}</div> : <div className="rounded-2xl border border-dashed border-base-300 p-8 text-center"><KeyRound className="mx-auto text-base-content/30" /><h3 className="mt-3 font-display text-lg font-semibold">No credentials issued</h3><p className="mt-1 text-sm text-base-content/50">Issue one when an adapter worker needs to submit observations.</p></div>}{revokeMutation.error && <ErrorState error={revokeMutation.error} />}</div>;
}

function CredentialForm({ submitting, error, onCancel, onCreate }: { submitting: boolean; error: unknown; onCancel: () => void; onCreate: (label: string, expiresAtUtc: string) => void }) { const [label, setLabel] = useState(""); const [expires, setExpires] = useState(defaultCredentialExpiry()); return <form className="mt-4 grid gap-4 rounded-xl bg-base-200 p-4 sm:grid-cols-[1fr_220px_auto] sm:items-end" onSubmit={(event) => { event.preventDefault(); onCreate(label.trim(), new Date(expires).toISOString()); }}><TextInput label="Credential label" value={label} onChange={setLabel} /><label className="form-control block"><span className="label-text mb-2 block text-sm font-semibold">Expires</span><input className="input input-bordered w-full" type="datetime-local" value={expires} min={localDateTimeValue(new Date())} onChange={(event) => setExpires(event.target.value)} required /></label><div className="flex gap-2"><button type="button" className="btn btn-ghost btn-sm" onClick={onCancel}>Cancel</button><button type="submit" className="btn btn-primary btn-sm" disabled={submitting || !label.trim()}>{submitting && <span className="loading loading-spinner loading-xs" />}Issue</button></div>{Boolean(error) && <div className="sm:col-span-3"><ErrorState error={error} /></div>}</form>; }
function IssuedToken({ result, onDone }: { result: CreateAdapterIngressCredentialResponse; onDone: () => void }) { const [copied, setCopied] = useState(false); async function copy() { await navigator.clipboard.writeText(result.token); setCopied(true); } return <section className="rounded-2xl border border-warning/30 bg-warning/8 p-4"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-warning" size={19} /><div><h3 className="font-semibold">Copy this token now</h3><p className="mt-1 text-sm text-base-content/60">BunkFy will not show the credential token again.</p></div></div><textarea className="textarea textarea-bordered mt-4 min-h-20 w-full break-all font-mono text-xs" readOnly value={result.token} onFocus={(event) => event.currentTarget.select()} /><div className="mt-3 flex justify-end gap-2"><button type="button" className="btn btn-ghost btn-sm" onClick={copy}>{copied ? <Check size={15} /> : <Clipboard size={15} />}{copied ? "Copied" : "Copy token"}</button><button type="button" className="btn btn-primary btn-sm" onClick={onDone}>I saved it</button></div></section>; }

function ConnectionConfirmation({ action, connection, submitting, error, onCancel, onConfirm }: { action: ConfirmAction; connection: AdapterConnection; submitting: boolean; error: unknown; onCancel: () => void; onConfirm: () => void }) { const copy = action === "enable" ? { title: "Enable this connection?", body: "Scheduled or remote processing may resume immediately.", button: "Enable connection", tone: "btn-primary" } : action === "disable" ? { title: "Disable this connection?", body: "New scheduled processing stops, but existing records and activity remain available.", button: "Disable connection", tone: "btn-error" } : action === "clear-schedule" ? { title: "Clear the polling schedule?", body: "The connection remains configured but will not be polled automatically.", button: "Clear schedule", tone: "btn-error" } : { title: "Reset the processing checkpoint?", body: `The adapter may replay records from its initial position. Current checkpoint: ${connection.checkpoint}`, button: "Reset checkpoint", tone: "btn-error" }; return <section className="rounded-2xl border border-warning/30 bg-warning/8 p-4"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-warning" size={19} /><div><h3 className="font-semibold">{copy.title}</h3><p className="mt-1 text-sm leading-6 text-base-content/60">{copy.body}</p></div></div>{Boolean(error) && <div className="mt-4"><ErrorState error={error} /></div>}<div className="mt-4 flex justify-end gap-2"><button type="button" className="btn btn-ghost btn-sm" onClick={onCancel}>Cancel</button><button type="button" className={`btn btn-sm ${copy.tone}`} onClick={onConfirm} disabled={submitting}>{submitting && <span className="loading loading-spinner loading-xs" />}{copy.button}</button></div></section>; }

function InfoRow({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="flex items-start gap-3 rounded-xl border border-base-300 p-4"><span className="mt-0.5 text-primary">{icon}</span><div className="min-w-0"><p className="text-xs text-base-content/40">{label}</p><p className="mt-1 break-all text-sm font-semibold">{value}</p></div></div>; }
function Metric({ label, value, tone }: { label: string; value: string | number; tone?: "warning" }) { return <div className={`rounded-xl border p-4 ${tone === "warning" ? "border-warning/25 bg-warning/8" : "border-base-300"}`}><p className="text-xs text-base-content/45">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>; }
function TextInput({ label, value, onChange, disabled = false }: { label: string; value: string; onChange: (value: string) => void; disabled?: boolean }) { return <label className="form-control block"><span className="label-text mb-2 block text-sm font-semibold">{label}</span><input className="input input-bordered w-full" value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} required={!disabled} /></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <label className="form-control block"><span className="label-text mb-2 block text-sm font-semibold">{label}</span><select className="select select-bordered w-full" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function executionModeKey(mode: AdapterConnection["executionMode"]): "polling" | "continuous" | "push" | "remotePolling" | "unknown" { if (typeof mode === "string") { const normalized = mode.replace(/[ -](.)/g, (_, letter: string) => letter.toUpperCase()); return (["polling", "continuous", "push", "remotePolling"] as const).find((value) => value.toLowerCase() === normalized.toLowerCase()) ?? "unknown"; } return ({ 1: "polling", 2: "continuous", 3: "push", 4: "remotePolling" } as const)[mode as 1 | 2 | 3 | 4] ?? "unknown"; }
function conflictPolicyKey(policy: AdapterConnection["conflictPolicy"]): "suggestionsOnly" | "autoApplyWhenAdapterBaselineUnchanged" { if (typeof policy === "string") return policy.toLowerCase().includes("suggestions") ? "suggestionsOnly" : "autoApplyWhenAdapterBaselineUnchanged"; return policy === 1 ? "suggestionsOnly" : "autoApplyWhenAdapterBaselineUnchanged"; }
function capabilityStatusLabel(status: number | string) { if (typeof status === "string") return status.replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase(); return ({ 1: "available", 2: "adapter type not registered", 3: "execution mode unsupported" } as Record<number, string>)[status] ?? "unknown"; }
function formatDuration(seconds: number) { if (seconds % 3600 === 0) return `${seconds / 3600}h`; if (seconds % 60 === 0) return `${seconds / 60}m`; return `${seconds}s`; }
function formatDateTime(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function timeAgo(value: string) { const seconds = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return `${seconds}s ago`; if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`; if (seconds < 86_400) return `${Math.floor(seconds / 3600)}h ago`; return `${Math.floor(seconds / 86_400)}d ago`; }
function emptyStringToNull(value: string) { const normalized = value.trim(); return normalized || null; }
function capitalize(value: string) { return value.slice(0, 1).toUpperCase() + value.slice(1); }
function localDateTimeValue(date: Date) { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60_000).toISOString().slice(0, 16); }
function defaultCredentialExpiry() { const date = new Date(); date.setDate(date.getDate() + 30); return localDateTimeValue(date); }
