import { useMutation, useQuery } from "@tanstack/react-query";
import { Activity, Braces, ChevronLeft, ChevronRight, Clock3, Database, Download, FileJson2, GitBranch, ListRestart, PlayCircle, Rows3 } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { useSearchParams } from "react-router-dom";
import { adapterExecutionModeLabel, ingestionRunStatusLabel, rawPayloadStatusLabel, receiptStatusLabel, reprocessingStatusLabel } from "../../api/labels";
import type { AdapterConnection, AdapterTypeCapability, IngestionRun, IngestionRunListResponse, ObservationParserCapabilityListResponse, ObservationReceipt, ObservationReceiptListResponse, ObservationReprocessingAttemptDetails, ObservationReprocessingAttemptListResponse } from "../../api/types";
import { ingestionRunNeedsLiveRefresh, LIVE_DETAIL_REFRESH_INTERVAL_MS, LIVE_LIST_REFRESH_INTERVAL_MS, receiptNeedsLiveRefresh, reprocessingNeedsLiveRefresh } from "../../app/liveUpdates";
import { useSession } from "../../app/session";
import { EmptyState, ErrorState, LoadingState, Modal, StatusBadge } from "../../components/ui/primitives";
import { SegmentedTabs } from "../../components/ui/SegmentedTabs";
import { SelectPicker } from "../../components/ui/SelectPicker";

const PAGE_SIZE = 30;
type ActivityTab = "runs" | "receipts" | "reprocessing" | "capabilities";

export function IngestionActivity({ propertyId, connections, adapterTypes, canReadRawPayloads }: { propertyId: string; connections: AdapterConnection[]; adapterTypes: AdapterTypeCapability[]; canReadRawPayloads: boolean }) {
  const [searchParams] = useSearchParams();
  const [tab, setTab] = useState<ActivityTab>(() => activityTab(searchParams.get("activity")));
  useEffect(() => setTab(activityTab(searchParams.get("activity"))), [searchParams]);
  return <div className="space-y-4"><SegmentedTabs value={tab} ariaLabel="Ingestion activity" onValueChange={setTab} options={[{ value: "runs", label: "Runs", icon: <PlayCircle size={15} /> }, { value: "receipts", label: "Receipts", icon: <Rows3 size={15} /> }, { value: "reprocessing", label: "Reprocessing", icon: <ListRestart size={15} /> }, { value: "capabilities", label: "Capabilities", icon: <Braces size={15} /> }]} />{tab === "runs" && <RunsPanel propertyId={propertyId} connections={connections} />}{tab === "receipts" && <ReceiptsPanel propertyId={propertyId} connections={connections} canReadRawPayloads={canReadRawPayloads} />}{tab === "reprocessing" && <ReprocessingPanel propertyId={propertyId} />}{tab === "capabilities" && <CapabilitiesPanel propertyId={propertyId} adapterTypes={adapterTypes} />}</div>;
}

function RunsPanel({ propertyId, connections }: { propertyId: string; connections: AdapterConnection[] }) {
  const { request } = useSession(); const [searchParams, setSearchParams] = useSearchParams(); const [page, setPage] = useState(1); const [connectionId, setConnectionId] = useState(""); useEffect(() => setPage(1), [connectionId]); const params = new URLSearchParams({ page: String(page), pageSize: String(PAGE_SIZE) }); if (connectionId) params.set("connectionId", connectionId); const runs = useQuery({ queryKey: ["ingestion-runs", propertyId, connectionId, page], queryFn: () => request<IngestionRunListResponse>(`/api/ingestion/properties/${propertyId}/runs?${params}`), refetchInterval: (query) => !searchParams.get("run") && query.state.data?.runs.some((item) => ingestionRunNeedsLiveRefresh(item.status)) ? LIVE_LIST_REFRESH_INTERVAL_MS : false, refetchIntervalInBackground: false }); function select(id: string | null) { const next = new URLSearchParams(searchParams); if (id) next.set("run", id); else next.delete("run"); setSearchParams(next, { replace: true }); } const items = runs.data?.runs ?? [];
  return <><ActivityCard title="Adapter runs" description="Execution history and processing outcomes." filter={<ConnectionFilter value={connectionId} connections={connections} onChange={setConnectionId} />}>{runs.isLoading ? <LoadingState label="Loading runs" /> : runs.error ? <div className="p-6"><ErrorState error={runs.error} retry={() => void runs.refetch()} /></div> : !items.length ? <div className="p-6"><EmptyState icon={<Activity />} title="No runs recorded" description="Adapter execution history will appear here." /></div> : <><div className="divide-y divide-base-300">{items.map((run) => <button key={run.runId} type="button" className="grid w-full gap-3 p-5 text-left transition hover:bg-base-200/70 sm:grid-cols-[1fr_auto_auto] sm:items-center sm:px-6" onClick={() => select(run.runId)}><div><p className="font-semibold">{connectionName(run.connectionId, connections)}</p><p className="mt-1 text-xs text-base-content/45">{run.observedCount} observed · {run.acceptedCount} accepted · {run.rejectedCount} rejected</p></div><time className="text-xs text-base-content/45">{formatDateTime(run.startedAtUtc)}</time><StatusBadge status={ingestionRunStatusLabel(run.status)} /></button>)}</div><Pagination page={page} total={runs.data?.totalCount ?? 0} onChange={setPage} /></>}</ActivityCard><RunDetail propertyId={propertyId} runId={searchParams.get("run")} connection={connections.find((item) => item.connectionId === runs.data?.runs.find((run) => run.runId === searchParams.get("run"))?.connectionId)} onClose={() => select(null)} /></>;
}

function RunDetail({ propertyId, runId, connection, onClose }: { propertyId: string; runId: string | null; connection?: AdapterConnection; onClose: () => void }) { const { request } = useSession(); const run = useQuery({ queryKey: ["ingestion-run", propertyId, runId], queryFn: () => request<IngestionRun>(`/api/ingestion/properties/${propertyId}/runs/${runId}`), enabled: Boolean(runId), refetchInterval: (query) => ingestionRunNeedsLiveRefresh(query.state.data?.status) ? LIVE_DETAIL_REFRESH_INTERVAL_MS : false, refetchIntervalInBackground: false }); const item = run.data; return <Modal open={Boolean(runId)} title="Ingestion run" description={item ? `${connection?.adapterType || "Adapter"} · ${item.runId.slice(0, 8).toUpperCase()}` : "Loading run"} onClose={onClose}>{run.isLoading ? <LoadingState label="Loading run" /> : run.error ? <ErrorState error={run.error} retry={() => void run.refetch()} /> : item ? <div className="space-y-5"><div className="flex items-center justify-between rounded-2xl bg-base-200 p-4"><div><p className="font-semibold">Started {formatDateTime(item.startedAtUtc)}</p><p className="mt-1 text-xs text-base-content/50">{item.completedAtUtc ? `Completed ${formatDateTime(item.completedAtUtc)}` : "Still running"}</p></div><StatusBadge status={ingestionRunStatusLabel(item.status)} /></div><div className="grid grid-cols-3 gap-3"><Metric label="Observed" value={item.observedCount} /><Metric label="Accepted" value={item.acceptedCount} /><Metric label="Rejected" value={item.rejectedCount} /></div><div className="grid gap-3 sm:grid-cols-2"><InfoRow icon={<GitBranch />} label="Starting checkpoint" value={item.startingCheckpoint || "None"} /><InfoRow icon={<GitBranch />} label="Accepted checkpoint" value={item.acceptedCheckpoint || "None"} /><InfoRow icon={<Activity />} label="Execution" value={executionKindLabel(item.executionKind)} /><InfoRow icon={<Clock3 />} label="Task attempt" value={item.taskAttempt != null ? String(item.taskAttempt) : "Not applicable"} /></div>{item.errorMessage && <div className="rounded-xl bg-error/8 p-4 text-sm text-error">{item.errorMessage}</div>}<div className="flex justify-end border-t border-base-300 pt-5"><button className="btn btn-ghost" onClick={onClose}>Close</button></div></div> : null}</Modal>; }

function ReceiptsPanel({ propertyId, connections, canReadRawPayloads }: { propertyId: string; connections: AdapterConnection[]; canReadRawPayloads: boolean }) { const { request } = useSession(); const [searchParams, setSearchParams] = useSearchParams(); const [page, setPage] = useState(1); const [connectionId, setConnectionId] = useState(""); useEffect(() => setPage(1), [connectionId]); const params = new URLSearchParams({ page: String(page), pageSize: String(PAGE_SIZE) }); if (connectionId) params.set("connectionId", connectionId); const receipts = useQuery({ queryKey: ["ingestion-receipts", propertyId, connectionId, page], queryFn: () => request<ObservationReceiptListResponse>(`/api/ingestion/properties/${propertyId}/receipts?${params}`), refetchInterval: (query) => !searchParams.get("receipt") && query.state.data?.receipts.some((item) => receiptNeedsLiveRefresh(item.status)) ? LIVE_LIST_REFRESH_INTERVAL_MS : false, refetchIntervalInBackground: false }); function select(id: string | null) { const next = new URLSearchParams(searchParams); if (id) next.set("receipt", id); else next.delete("receipt"); setSearchParams(next, { replace: true }); } const items = receipts.data?.receipts ?? [];
  return <><ActivityCard title="Observation receipts" description="Every source record accepted or rejected by ingestion." filter={<ConnectionFilter value={connectionId} connections={connections} onChange={setConnectionId} />}>{receipts.isLoading ? <LoadingState label="Loading receipts" /> : receipts.error ? <div className="p-6"><ErrorState error={receipts.error} retry={() => void receipts.refetch()} /></div> : !items.length ? <div className="p-6"><EmptyState icon={<Database />} title="No receipts recorded" description="Adapter observations will appear here after ingestion begins." /></div> : <><div className="divide-y divide-base-300">{items.map((receipt) => <button key={receipt.receiptId} type="button" className="grid w-full gap-3 p-5 text-left transition hover:bg-base-200/70 sm:grid-cols-[1fr_auto_auto] sm:items-center sm:px-6" onClick={() => select(receipt.receiptId)}><div className="min-w-0"><p className="truncate font-semibold">{receipt.sourceRecordType} · {receipt.externalId}</p><p className="mt-1 truncate text-xs text-base-content/45">{connectionName(receipt.connectionId, connections)}{receipt.parserType ? ` · ${receipt.parserType} v${receipt.parserVersion}` : ""}</p></div><time className="text-xs text-base-content/45">{formatDateTime(receipt.receivedAtUtc)}</time><StatusBadge status={receiptStatusLabel(receipt.status)} /></button>)}</div><Pagination page={page} total={receipts.data?.totalCount ?? 0} onChange={setPage} /></>}</ActivityCard><ReceiptDetail propertyId={propertyId} receiptId={searchParams.get("receipt")} canReadRawPayloads={canReadRawPayloads} onClose={() => select(null)} /></>;
}

function ReceiptDetail({ propertyId, receiptId, canReadRawPayloads, onClose }: { propertyId: string; receiptId: string | null; canReadRawPayloads: boolean; onClose: () => void }) { const { request, download } = useSession(); const receipt = useQuery({ queryKey: ["ingestion-receipt", propertyId, receiptId], queryFn: () => request<ObservationReceipt>(`/api/ingestion/properties/${propertyId}/receipts/${receiptId}`), enabled: Boolean(receiptId), refetchInterval: (query) => receiptNeedsLiveRefresh(query.state.data?.status) ? LIVE_DETAIL_REFRESH_INTERVAL_MS : false, refetchIntervalInBackground: false }); const downloadMutation = useMutation({ mutationFn: async () => { const result = await download(`/api/ingestion/properties/${propertyId}/receipts/${receiptId}/raw-payload`); const url = URL.createObjectURL(result.blob); try { const anchor = document.createElement("a"); anchor.href = url; anchor.download = result.fileName || `ingestion-receipt-${receiptId}.payload`; anchor.click(); } finally { URL.revokeObjectURL(url); } } }); const item = receipt.data; const rawAvailable = item && rawPayloadStatusLabel(item.rawPayloadStatus) === "available";
  return <Modal open={Boolean(receiptId)} size="lg" title={item ? `${item.sourceRecordType} observation` : "Observation receipt"} description={item ? `External ID ${item.externalId}` : "Loading receipt"} onClose={onClose}>{receipt.isLoading ? <LoadingState label="Loading receipt" /> : receipt.error ? <ErrorState error={receipt.error} retry={() => void receipt.refetch()} /> : item ? <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-base-200 p-4"><div><p className="font-semibold">Received {formatDateTime(item.receivedAtUtc)}</p><p className="mt-1 text-xs text-base-content/50">Observed {formatDateTime(item.observedAtUtc)}</p></div><StatusBadge status={receiptStatusLabel(item.status)} /></div><div className="grid gap-3 sm:grid-cols-2"><InfoRow icon={<FileJson2 />} label="Source record" value={item.sourceRecordType} /><InfoRow icon={<Database />} label="External ID" value={item.externalId} /><InfoRow icon={<GitBranch />} label="Source revision" value={item.sourceRevision || "Not provided"} /><InfoRow icon={<Braces />} label="Parser" value={item.parserType ? `${item.parserType} v${item.parserVersion}` : "Not parsed"} /><InfoRow icon={<FileJson2 />} label="Raw payload" value={`${capitalize(rawPayloadStatusLabel(item.rawPayloadStatus))} until ${formatDateTime(item.rawPayloadRetainUntilUtc)}`} /><InfoRow icon={<GitBranch />} label="Content hash" value={item.contentHash} /></div>{item.rejectionReason && <div className="rounded-xl bg-error/8 p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-error/70">Rejection reason</p><p className="mt-2 text-sm text-error">{item.rejectionReason}</p></div>}{downloadMutation.error && <ErrorState error={downloadMutation.error} />}<div className="flex flex-wrap justify-end gap-2 border-t border-base-300 pt-5">{canReadRawPayloads && rawAvailable && <button type="button" className="btn btn-primary" onClick={() => downloadMutation.mutate()} disabled={downloadMutation.isPending}><Download size={16} />{downloadMutation.isPending ? "Preparing…" : "Download raw payload"}</button>}<button className="btn btn-ghost" onClick={onClose}>Close</button></div></div> : null}</Modal>; }

function ReprocessingPanel({ propertyId }: { propertyId: string }) { const { request } = useSession(); const [searchParams, setSearchParams] = useSearchParams(); const [page, setPage] = useState(1); const attempts = useQuery({ queryKey: ["ingestion-reprocessing", propertyId, page], queryFn: () => request<ObservationReprocessingAttemptListResponse>(`/api/ingestion/properties/${propertyId}/reprocessing-attempts?page=${page}&pageSize=${PAGE_SIZE}`), refetchInterval: (query) => !searchParams.get("attempt") && query.state.data?.attempts.some((item) => reprocessingNeedsLiveRefresh(item.status)) ? LIVE_LIST_REFRESH_INTERVAL_MS : false, refetchIntervalInBackground: false }); function select(id: string | null) { const next = new URLSearchParams(searchParams); if (id) next.set("attempt", id); else next.delete("attempt"); setSearchParams(next, { replace: true }); } const items = attempts.data?.attempts ?? [];
  return <><ActivityCard title="Reprocessing attempts" description="Audit retained observations parsed again with a selected parser.">{attempts.isLoading ? <LoadingState label="Loading reprocessing" /> : attempts.error ? <div className="p-6"><ErrorState error={attempts.error} retry={() => void attempts.refetch()} /></div> : !items.length ? <div className="p-6"><EmptyState icon={<ListRestart />} title="No reprocessing attempts" description="Reprocessing activity will appear here when retained observations are replayed." /></div> : <><div className="divide-y divide-base-300">{items.map((attempt) => <button key={attempt.attemptId} type="button" className="grid w-full gap-3 p-5 text-left transition hover:bg-base-200/70 sm:grid-cols-[1fr_auto_auto] sm:items-center sm:px-6" onClick={() => select(attempt.attemptId)}><div><p className="font-semibold">{attempt.parserType} v{attempt.parserVersion}</p><p className="mt-1 text-xs text-base-content/45">{attempt.parsedCount} parsed · {attempt.acceptedCount} accepted · {attempt.rejectedCount} rejected</p></div><time className="text-xs text-base-content/45">{formatDateTime(attempt.requestedAtUtc)}</time><StatusBadge status={reprocessingStatusLabel(attempt.status)} /></button>)}</div><Pagination page={page} total={attempts.data?.totalCount ?? 0} onChange={setPage} /></>}</ActivityCard><ReprocessingDetail propertyId={propertyId} attemptId={searchParams.get("attempt")} onClose={() => select(null)} /></>;
}

function ReprocessingDetail({ propertyId, attemptId, onClose }: { propertyId: string; attemptId: string | null; onClose: () => void }) { const { request } = useSession(); const details = useQuery({ queryKey: ["ingestion-reprocessing-attempt", propertyId, attemptId], queryFn: () => request<ObservationReprocessingAttemptDetails>(`/api/ingestion/properties/${propertyId}/reprocessing-attempts/${attemptId}`), enabled: Boolean(attemptId), refetchInterval: (query) => reprocessingNeedsLiveRefresh(query.state.data?.attempt.status) ? LIVE_DETAIL_REFRESH_INTERVAL_MS : false, refetchIntervalInBackground: false }); const item = details.data?.attempt; return <Modal open={Boolean(attemptId)} size="lg" title={item ? `${item.parserType} reprocessing` : "Reprocessing attempt"} description={item ? `Attempt ${item.attemptId.slice(0, 8).toUpperCase()}` : "Loading attempt"} onClose={onClose}>{details.isLoading ? <LoadingState label="Loading reprocessing attempt" /> : details.error ? <ErrorState error={details.error} retry={() => void details.refetch()} /> : item ? <div className="space-y-5"><div className="flex items-center justify-between rounded-2xl bg-base-200 p-4"><div><p className="font-semibold">Requested {formatDateTime(item.requestedAtUtc)}</p><p className="mt-1 text-xs text-base-content/50">Parser version {item.parserVersion} · task attempt {item.lastTaskAttempt}</p></div><StatusBadge status={reprocessingStatusLabel(item.status)} /></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Parsed" value={item.parsedCount} /><Metric label="Accepted" value={item.acceptedCount} /><Metric label="Duplicates" value={item.duplicateCount} /><Metric label="Rejected" value={item.rejectedCount} /></div>{item.lastErrorCode && <div className="rounded-xl bg-error/8 p-4 text-sm text-error">{item.lastErrorCode}</div>}<section><h3 className="font-display text-lg font-semibold">Outputs</h3>{details.data?.outputs.length ? <div className="mt-3 space-y-2">{details.data.outputs.map((output) => <div key={output.outputIndex} className="grid gap-2 rounded-xl border border-base-300 p-3 text-sm sm:grid-cols-[60px_1fr_auto] sm:items-center"><span className="font-mono text-xs text-base-content/45">#{output.outputIndex}</span><div><p className="font-semibold">{output.recordType} · {output.externalId}</p><p className="mt-1 text-xs text-base-content/45">{output.errorCode || output.contentHash}</p></div><StatusBadge status={outputStatusLabel(output.status)} /></div>)}</div> : <p className="mt-3 rounded-xl border border-dashed border-base-300 p-5 text-center text-sm text-base-content/50">No parser outputs were recorded.</p>}</section><div className="flex justify-end border-t border-base-300 pt-5"><button className="btn btn-ghost" onClick={onClose}>Close</button></div></div> : null}</Modal>; }

function CapabilitiesPanel({ propertyId, adapterTypes }: { propertyId: string; adapterTypes: AdapterTypeCapability[] }) { const { request } = useSession(); const parsers = useQuery({ queryKey: ["ingestion-parser-types", propertyId], queryFn: () => request<ObservationParserCapabilityListResponse>(`/api/ingestion/properties/${propertyId}/parser-types`) }); return <div className="grid gap-5 xl:grid-cols-2"><section className="card border border-base-300 bg-base-100 shadow-sm"><div className="card-body p-5"><h2 className="font-display text-xl font-semibold">Adapter capabilities</h2><p className="text-sm text-base-content/50">Execution modes currently registered with BunkFy.</p><div className="mt-2 space-y-3">{adapterTypes.map((adapter) => <article key={adapter.adapterType} className="rounded-xl border border-base-300 p-4"><h3 className="font-semibold">{adapter.adapterType}</h3><p className="mt-1 text-xs text-base-content/45">Protocol v{adapter.protocolVersion} · configuration schema v{adapter.configurationSchemaVersion}</p><div className="mt-3 flex flex-wrap gap-2">{adapter.executionModes.map((mode) => <span key={String(mode)} className="badge badge-ghost capitalize">{adapterExecutionModeLabel(mode)}</span>)}</div></article>)}{!adapterTypes.length && <p className="rounded-xl border border-dashed border-base-300 p-5 text-center text-sm text-base-content/50">No adapter types are registered.</p>}</div></div></section><section className="card border border-base-300 bg-base-100 shadow-sm"><div className="card-body p-5"><h2 className="font-display text-xl font-semibold">Parser capabilities</h2><p className="text-sm text-base-content/50">Parsers available for retained-observation reprocessing.</p>{parsers.isLoading ? <LoadingState label="Loading parsers" /> : parsers.error ? <ErrorState error={parsers.error} retry={() => void parsers.refetch()} /> : <div className="mt-2 space-y-3">{parsers.data?.parsers.map((parser) => <article key={`${parser.parserType}-${parser.parserVersion}`} className="rounded-xl border border-base-300 p-4"><h3 className="font-semibold">{parser.parserType} v{parser.parserVersion}</h3><p className="mt-2 text-xs text-base-content/50">Inputs: {parser.supportedSourceRecordTypes.join(", ") || "None"}</p><p className="mt-1 text-xs text-base-content/50">Outputs: {parser.outputRecordTypes.join(", ") || "None"}</p></article>)}{!parsers.data?.parsers.length && <p className="rounded-xl border border-dashed border-base-300 p-5 text-center text-sm text-base-content/50">No parser types are registered.</p>}</div>}</div></section></div>; }

function ActivityCard({ title, description, filter, children }: { title: string; description: string; filter?: ReactNode; children: ReactNode }) { return <section className="card border border-base-300 bg-base-100 shadow-sm"><div className="flex flex-col gap-3 border-b border-base-300 p-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><h2 className="font-display text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-base-content/50">{description}</p></div>{filter}</div>{children}</section>; }
function ConnectionFilter({ value, connections, onChange }: { value: string; connections: AdapterConnection[]; onChange: (value: string) => void }) { return <SelectPicker className="w-full sm:w-56" size="sm" ariaLabel="Filter by connection" value={value || "all"} onValueChange={(next) => onChange(next === "all" ? "" : next)} options={[{ value: "all", label: "All connections" }, ...connections.map((connection) => ({ value: connection.connectionId, label: `${connection.adapterType} · ${connection.connectionId.slice(0, 6)}` }))]} />; }
function Pagination({ page, total, onChange }: { page: number; total: number; onChange: (page: number) => void }) { return <div className="flex items-center justify-between border-t border-base-300 px-4 py-3 sm:px-6"><p className="text-xs text-base-content/45">{total} total · page {page}</p><div className="join"><button className="btn btn-sm join-item" disabled={page === 1} onClick={() => onChange(page - 1)} aria-label="Previous page"><ChevronLeft size={16} /></button><button className="btn btn-sm join-item" disabled={page * PAGE_SIZE >= total} onClick={() => onChange(page + 1)} aria-label="Next page"><ChevronRight size={16} /></button></div></div>; }
function InfoRow({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="flex items-start gap-3 rounded-xl border border-base-300 p-4"><span className="mt-0.5 text-primary">{icon}</span><div className="min-w-0"><p className="text-xs text-base-content/40">{label}</p><p className="mt-1 break-all text-sm font-semibold">{value}</p></div></div>; }
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-base-300 p-4 text-center"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-base-content/45">{label}</p></div>; }
function connectionName(id: string, connections: AdapterConnection[]) { const connection = connections.find((item) => item.connectionId === id); return connection ? `${connection.adapterType} · ${id.slice(0, 6).toUpperCase()}` : `Connection ${id.slice(0, 8).toUpperCase()}`; }
function executionKindLabel(value: number | string) { if (typeof value === "string") return humanize(value); return ({ 1: "Task runtime", 2: "Remote lease" } as Record<number, string>)[value] ?? "Unknown"; }
function outputStatusLabel(value: number | string) { if (typeof value === "string") return humanize(value); return ({ 1: "accepted", 2: "duplicate", 3: "rejected" } as Record<number, string>)[value] ?? "unknown"; }
function humanize(value: string) { return value.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/^./, (letter) => letter.toUpperCase()); }
function capitalize(value: string) { return value.slice(0, 1).toUpperCase() + value.slice(1); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function activityTab(value: string | null): ActivityTab { return value === "receipts" || value === "reprocessing" || value === "capabilities" ? value : "runs"; }
